
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kajmpwwojrggqfaxwmqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtham1wd3dvanJnZ3FmYXh3bXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzI3MzEsImV4cCI6MjA1Njc0ODczMX0.jLUA6zW6LpN_PyG897s35vBcEBLGN2B-uyjG3m2qhdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
